name: Enable "Vernuntii" in subsequent MSBuild calls
description: Enables "Vernuntii"-.targets file in subsequent calls of MSBuild

inputs:
  binary:
    default: "vernuntii"
    description: Binary to use Vernuntii
    required: false
  property:
    # https://docs.microsoft.com/en-US/visualstudio/msbuild/customize-your-build?view=vs-2022#customize-all-net-builds
    # https://blog.postsharp.net/post/under-the-hood-of-msbuild-integration.html
    default: CustomBeforeMicrosoftCommonProps
    description: MSBuild property name to populate with "Vernuntii"-.targets file location
    required: false
  verbose:
    default: ""
    description: "See console executable help for more informations"
    required: false
  config-path:
    default: ""
    description: "See console executable help for more informations"
    required: false
  cache-id:
    default: ""
    description: "The cache id is used to cache the version informations once and load them on next accesses"
    required: false
  cache-creation-retention-time:
    default: ""
    description: "The cache retention time since creation"
    required: false
  cache-last-access-retention-time:
    default: ""
    description: "The cache retention time since last access"
    required: false
  empty-caches:
    default: ""
    description: "Indicates that the caches should be emptied where version informations are stored. This happens before the cache process itself"
    required: false

runs:
  using: composite
  steps:
    - id: args
      run: |
        [ ! -x "$(which ${{ inputs.binary }})" ] \
        && echo "Binary '${{ inputs.binary }}' does not exist or is not executable" >&2 \
        && exit 1

        echo "${{ inputs.property }}=$(${{ inputs.binary }} location MSBuildTargets)" >> $GITHUB_ENV

        # Customizations for "Vernuntii"-.targets file
        echo "VernuntiiAssemblyFile=$(vernuntii location MSBuildDll)" >> $GITHUB_ENV
        echo "VernuntiiConsoleExecutableFile=$(vernuntii location ConsoleDll)" >> $GITHUB_ENV

        # Further "Vernuntii"-.targets customizations
        [ '${{ inputs.verbose }}' != '' ] && echo "VernuntiiVerbose=${{ inputs.verbose }}" >> $GITHUB_ENV
        [ '${{ inputs.config-path }}' != '' ] && echo "VernuntiiConfigPath=${{ inputs.config-path }}" >> $GITHUB_ENV
        [ '${{ inputs.cache-id }}' != '' ] && echo "VernuntiiCacheId=${{ inputs.cache-id }}" >> $GITHUB_ENV
        [ '${{ inputs.cache-creation-retention-time }}' != '' ] && echo "VernuntiiCacheCreationRetentionTime=${{ inputs.cache-creation-retention-time }}" >> $GITHUB_ENV
        [ '${{ inputs.cache-last-access-retention-time }}' != '' ] && echo "VernuntiiCacheLastAccessRetentionTime=${{ inputs.cache-last-access-retention-time }}" >> $GITHUB_ENV
        [ '${{ inputs.empty-caches }}' != '' ] && echo "VernuntiiEmptyCaches=${{ inputs.empty-caches }}" >> $GITHUB_ENV

        exit 0
      shell: bash
