name: "Lockdown repository"

on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    if: ${{ github.repository == "versionable-messages/actions" }}
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          issue-comment: >
            This repository does not accept bug reports,
            see the README for details.
          skip-closed-issue-comment: true
          pr-comment: >
            This repository does not accept pull requests,
            see the README for details.
          skip-closed-pr-comment: true
